# Change these first
owner: Babsy-IT # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Babsy
    url: https://www.babsy.ch
    assignees:
      - Oliver-Babsy
      - stefan-ffr
      - Babsy-IT
  - name: Babsy Verein
    url: https://verein.babsy.ch
    assignees:
      - Oliver-Babsy
      - stefan-ffr
  - name: Babsy Jitsi
    url: https://jitsi.babsy.ch
    assignees:
      - stefan-ffr
  - name: Babsy Bitwarden Passwortmanager
    url: https://bitwarden.babsy.ch
    assignees:
      - stefan-ffr
      - Oliver-Babsy
  - name: Babsy Newslettertool Listmonk
    url: https://newsletter.babsy.ch
    assignees:
      - stefan-ffr
      - Oliver-Babsy


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.babsy.ch
  # baseUrl: /uptime
  logoUrl: https://babsy.ch/wp-content/uploads/2021/12/cropped-babsy-logo-1.png
  name: Babsy-Uptime Monitoring
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for Babsy
  navbar:
    - title: Babsy
      href: https://www.babsy.ch
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
